application: logperiod
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /doc
  static_dir: doc

- url: /prog
  static_dir: prog

- url: /data
  static_dir: data

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /.*
  script: logperiod.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

