application: logperiod
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /prog
  static_dir: prog

- url: /data
  static_dir: data

- url: /.*
  script: logperiod.py

